# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CMY4fMPVwt9PI-j7VxZM7UXnMo0r4RrI
"""

#!pip install gradio

import gradio as gr
import joblib
import numpy as np

model = joblib.load('Diabetes_model_for_Dia.joblib')

def predict(gender, age, hypertension, heart_disease, smoking_history, bmi, HbA1c_level, blood_glucose_level):
  # Convert inputs to appropriate types
  gender = int(gender)
  age = int(age)
  hypertension = int(hypertension)
  heart_disease = int(heart_disease)
  smoking_history = int(smoking_history)
  bmi = float(bmi)
  HbA1c_level = float(HbA1c_level)
  blood_glucose_level = int(blood_glucose_level)

  # Prepare the input data as a list
  input_data = np.array([gender, age, hypertension, heart_disease, smoking_history, bmi, HbA1c_level, blood_glucose_level]).reshape(1, -1)

  # Make prediction using the loaded model
  prediction = model.predict(input_data)
  return prediction[0]
# Create the Gradio interface
interface = gr.Interface(
    fn=predict,
    inputs=[
        gr.Textbox(label="Gender (0/1)"),
        gr.Textbox(label="Age"),
        gr.Textbox(label="Hypertension (0 or 1)"),
        gr.Textbox(label="Heart Disease (0 or 1)"),
        gr.Textbox(label="Smoking History (0 or 1)"),
        gr.Textbox(label="BMI"),
        gr.Textbox(label="HbA1c Level"),
        gr.Textbox(label="Blood Glucose Level")
    ],
    outputs="text",
    title="Diabetes Predictor",
    description="Enter the patient's data to predict the likelihood of diabetes."
)

# Launch the app
interface.launch()